backend:
  name: github
  repo: Ten-3/letts-law

media_folder: "images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
  - label: "Blog posts"
    name: "blog-post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog-post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Thumbnail image"
        name: "thumb"
        widget: "image"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Banner Image"
        name: "banner"
        widget: "image"
