backend:
  name: github
  repo: ten-3/letts-law

media_folder: "images/uploads"

collections:
  - label: "Blog posts"
    name: "blog-post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog-post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image"
        name: "image"
        widget: "image"



      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "cottage"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Thumbnail image"
        name: "thumb"
        widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Photos"
        name: "photos"
        widget: "list"
        fields:
          - label: "Image"
            name: "url"
            widget: "image"
          - label: "Caption"
            name: "caption"
            widget: "string"
