backend:
  name: github
  repo: ten-3/letts-law

media_folder: "images/uploads"

collections:
  - label: "Blog Post"
    name: "blog-post"
    file: "_layouts/blog-post.html"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Body"
      name: "body"
      widget: "markdown"
