backend:
  name: github
  repo: ten-3/letts-law

media_folder: "images/uploads"

collections:
  - label: "Blog Post"
    name: "blog-post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog-post"
      - label: "Title"
        name: "title"
        widget: "string"
